import * as THREE from 'three';
import { book } from './book/Book'; import { SceneManager } from './scenes/SceneManager'; import { AudioManager } from './audio/AudioManager'; import { SaveManager } from './core/SaveManager';
import './style.css';
const app = document.querySelector<HTMLDivElement>('#app')!; const audio = new AudioManager(); const save = new SaveManager(); let chapterIndex = Number(save.load().chapterIndex || 0); let state = 'TITLE'; let reading = false;
app.innerHTML = `<main class="shell"><section id="title" class="title"><p class="eyebrow">AN INTERACTIVE LITERARY EDITION</p><h1>CRIME<br><i>AND</i> PUNISHMENT</h1><p class="author">Fyodor Dostoevsky</p><button id="enter">ENTER</button><p class="edition">Public-domain translation · Constance Garnett</p></section><section id="world" class="world hidden"><div id="canvas"></div><header><button class="brand" id="home">CRIME / PUNISHMENT</button><nav><button data-view="read">READ</button><button data-view="scene">ENTER SCENE</button><button data-view="listen">LISTEN</button><button data-view="about">ABOUT</button></nav></header><aside id="panel" class="panel"></aside><div id="hint" class="hint">Move through the room. Select an object.</div><div class="controls"><button id="prev">← PREVIOUS</button><span id="progress"></span><button id="next">NEXT →</button></div></section></main>`;
const title = document.querySelector('#title')!; const world = document.querySelector('#world')!; const panel = document.querySelector('#panel')!; const hint = document.querySelector('#hint')!; const progress = document.querySelector('#progress')!;
const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; document.querySelector('#canvas')!.append(renderer.domElement); const scene = new THREE.Scene(); scene.background = new THREE.Color(0x171513); scene.fog = new THREE.Fog(0x171513, 8, 18); const camera = new THREE.PerspectiveCamera(34, innerWidth / innerHeight, .1, 100); camera.position.set(7, 5.2, 8); camera.lookAt(0, 1.8, 0); const light = new THREE.HemisphereLight(0xbbb6a8, 0x15100d, 1.4); scene.add(light); const lamp = new THREE.PointLight(0xd3ad79, 18, 12); lamp.position.set(-1, 4, 2); lamp.castShadow = true; scene.add(lamp); const manager = new SceneManager(scene, interact); manager.load('raskolnikov-room');
function renderReader() { const c = book.chapters[chapterIndex]; panel.innerHTML = `<div class="panel-top"><span>PART I · ${c.title}</span><button id="close">×</button></div><article><h2>${c.title}</h2>${c.text.map((p: string) => `<p>${p}</p>`).join('')}<div class="reflection"><span>REFLECT</span><p>${c.reflection}</p></div></article>`; panel.classList.add('open'); reading = true; state = 'READING'; }
function showAbout() { panel.innerHTML = `<div class="panel-top"><span>ABOUT THIS EDITION</span><button id="close">×</button></div><article><h2>A book as a place.</h2><p>This is an original procedural interpretation of Dostoevsky's novel: text remains the source of truth, while each scene offers a quiet space to dwell.</p><p><b>Edition:</b> Constance Garnett, 1914, public domain.</p><p><b>Technology:</b> Three.js · Web Audio API · TypeScript · Vite</p><p class="small">The 3D room is an interpretive scene. It is not a replacement for the text.</p></article>`; panel.classList.add('open'); }
function interact(id: string) { audio.click(); if (id === 'table') renderReader(); else if (id === 'window') hint.textContent = 'Beyond the dirty glass: heat, dust, and the city breathing.'; else if (id === 'door') renderReader(); else if (id === 'bed') hint.textContent = 'The bed is too narrow to rest in, and the room will not let you sleep.'; else hint.textContent = 'The chair faces the table. Nothing has been resolved.'; }
(document.querySelector('#enter') as HTMLButtonElement).onclick = () => { audio.start(); title.classList.add('hidden'); world.classList.remove('hidden'); state = 'SCENE'; };
document.querySelectorAll('[data-view]').forEach(b => b.addEventListener('click', () => { const v = (b as HTMLElement).dataset.view; if (v === 'read' || v === 'listen') renderReader(); if (v === 'scene') { panel.classList.remove('open'); state = 'SCENE'; } if (v === 'about') showAbout(); }));
document.querySelector('#close')?.addEventListener('click', () => panel.classList.remove('open'));
document.querySelector('#prev')!.addEventListener('click', () => { if (chapterIndex > 0) { chapterIndex--; save.save({ chapterIndex }); renderReader(); } }); document.querySelector('#next')!.addEventListener('click', () => { if (chapterIndex < book.chapters.length - 1) { chapterIndex++; save.save({ chapterIndex }); renderReader(); } });
const raycaster = new THREE.Raycaster(); const pointer = new THREE.Vector2(); renderer.domElement.addEventListener('pointerdown', e => { pointer.x = (e.clientX / innerWidth) * 2 - 1; pointer.y = -(e.clientY / innerHeight) * 2 + 1; raycaster.setFromCamera(pointer, camera); const objects = manager.current?.interactions || []; const hit = raycaster.intersectObjects(objects.map(i => i.object), false)[0]; if (hit) objects.find(i => i.object === hit.object)?.onInteract(); });
addEventListener('resize', () => { camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); renderer.setSize(innerWidth, innerHeight); }); let last = 0; function loop(t: number) { const d = Math.min((t - last) / 1000, .1); last = t; manager.update(d); progress.textContent = `CHAPTER ${chapterIndex + 1} / ${book.chapters.length}`; renderer.render(scene, camera); requestAnimationFrame(loop); } requestAnimationFrame(loop);
